Cancel visual mode when switching editor
vscode-neovim/vscode-neovim pull request #1578
Opened 2023-10-29 15:13 UTC by trkoch

Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1577

2023-10-29 15:32 UTC, trkoch commented
Note I "fixed" a test by changing the assertion. Judging from the title _Current mode is canceled when switching between editor panes_ I feel this makes more sense now.

2023-10-29 15:36 UTC, xiyaowong commented
Off-topic, I think there are too many logs now, one log per step...😂

2023-10-29 16:03 UTC, xiyaowong requested changes

2023-10-29 16:26 UTC, theol0403 commented on src/buffer_manager.ts
> +            if (this.main.modeManager.isVisualMode) {
I think insert should stay in insert, but I am good with canceling visual.

2023-10-29 18:37 UTC, trkoch commented on src/buffer_manager.ts
> +            if (this.main.modeManager.isVisualMode) {
@theol0403 I agree insert should stay in insert. It's intended behavior introduced with https://github.com/vscode-neovim/vscode-neovim/pull/1050, and consistent with vim.

2023-10-29 18:45 UTC, trkoch commented on src/buffer_manager.ts
> +            if (this.main.modeManager.isVisualMode) {
@xiyaowong Not sure about cmdline editing. Do you have a use case? Personally, I find `if (this.main.modeManager.isVisualMode)` more intention-revealing, but thats probably a matter of style. In any case, I suggest to keep this PR focused on fixing the referenced bug.

2023-10-29 18:54 UTC, trkoch commented
> Off-topic, I think there are too many logs now, one log per step...😂

@xiyaowong Yeah. It's pretty crazy. It did help me though with debugging this issue.

2023-10-29 19:03 UTC, theol0403 approved these changes

2023-10-29 19:04 UTC, theol0403 approved these changes

2023-10-29 19:05 UTC, merged

2023-11-13 13:55 UTC, justinmk commented on src/buffer_manager.ts
> +                await this.client.input("<Esc>");
`:help interrupt()` may be more ideal than inputting ESC.