bug: Match any ASCII characters in composite keys
vscode-neovim/vscode-neovim pull request #1923
Opened 2024-04-30 20:21 UTC by uduse

Ref Issue: #1922

Ref: https://stackoverflow.com/questions/3203190/regex-any-ascii-character

2024-04-30 23:03 UTC, xiyaowong requested changes

2024-04-30 23:03 UTC, xiyaowong commented on src/typing_manager.ts
>                      `Invalid composite key: ${key}. Composite key must be exactly 2 characters long.`,
```suggestion
                    `Invalid composite key: ${key}. Composite key must be exactly 2 ASCII characters long.`,
```

2024-04-30 23:10 UTC, xiyaowong commented
Should also change config schema in package.json?

2024-05-01 00:46 UTC, uduse commented
@xiyaowong I don't understand what else need to be changed. Can you help me here?

2024-05-01 12:27 UTC, xiyaowong approved these changes

2024-05-01 12:29 UTC, merged