refactor: Improve usability of afterInitConfig option in the settings
vscode-neovim/vscode-neovim pull request #2167
Opened 2024-07-18 13:39 UTC by nottnottloop

I spent around 15 minutes wondering why my Vimscript wasn't working to ignore case. Below you can see the settings for the current version of the extension, the top is the correct line and the bottom is the line I was writing:
![image](https://github.com/user-attachments/assets/2c223913-e3f8-4047-8956-485a42cfbff7)

Which maps to this in settings.json
![image](https://github.com/user-attachments/assets/ffc27d1a-8801-4ce8-9e25-640512086010)

I think I would have easily understood what to do immediately if the instructions looked like this instead:
![Screenshot 2024-07-18 143434](https://github.com/user-attachments/assets/7141d828-25d2-4d5f-9d02-1cb822daf524)

2024-07-18 13:43 UTC, ollien commented on package-lock.json
> -                "vscode": "^1.87.0"
Is this necessary as part of your changeset?

2024-07-18 13:44 UTC, ollien reviewed
LGTM, barring the errant(?) package lock changes. Thanks for the contribution!

2024-07-18 14:05 UTC, nottnottloop commented
> LGTM, barring the errant(?) package lock changes. Thanks for the contribution!

Sorry I'm not very good at this. My bad!!

2024-07-18 14:11 UTC, nottnottloop commented
Package-lock changes are removed from my branch

2024-07-18 14:23 UTC, xiyaowong commented
The modified example is incorrect.

2024-07-18 14:25 UTC, nottnottloop commented
> The modified example is incorrect. The `EOF` is missing.

Should it have the original array or should it have the original array with `set ignorecase` in it as well, what do you think

2024-07-18 14:27 UTC, xiyaowong requested changes

2024-07-18 14:27 UTC, xiyaowong commented on package.json
> +                    "markdownDescription": "Config to be sourced after init config. Each item is a different line of the config. For example:\n\n`echo 'hello'`\n\n`lua << EOF`\n\n`require'vscode'.not
```suggestion
                    "markdownDescription": "Config to be sourced after init config. Each item is a different line of the config. For example:\n\n`echo 'hello'`\n\n`lua << EOF`\n\n`require'vscode'.notify('world')`\n\n`EOF`"
```

2024-07-18 14:29 UTC, xiyaowong commented
> I wanted to demonstrate another example that might be useful

This is okay, just make sure the example works correctly.

2024-07-18 14:36 UTC, nottnottloop commented
After latest change
![image](https://github.com/user-attachments/assets/4b07d747-a9b9-4f17-b767-d526a02b595a)

2024-07-18 14:42 UTC, xiyaowong approved these changes
How about putting `set ignorecase` on the first line? 👀

2024-07-18 14:47 UTC, nottnottloop commented
> How about putting `set ignorecase` on the first line? 👀

![image](https://github.com/user-attachments/assets/27e47807-d992-49f5-8101-1c60d92b205e)
No worries, I love a good `set ignorecase`. Wait, did you mean only four lines with `echo 'hello'` removed or the whole five lines like above?

In case it isn't obvious I only use Vim motions, and have never really gone deep on Neovim configuration properly, so I didn't know what I was changing really w.r.t `EOF`.

2024-07-19 00:32 UTC, xiyaowong commented
I just realized where the original misleading aspect was. VSCode offers "Add Item". I've hardly used the settings UI. I think other options also need to consider this issue. Contributions are welcome.

2024-07-19 00:34 UTC, merged